/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:01516abd-2a98-4f23-8f62-8f01fe92f4c1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_4MyWGHxc9",
    "aws_user_pools_web_client_id": "64gmkf7pt95au964liu1g16tju",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL",
        "FAMILY_NAME",
        "NAME"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://xo2fx7jhtzar3azhqvq2rwiumm.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-mkoxte5ch5aljitpuiey4x3bui",
    "aws_user_files_s3_bucket": "smartstudy-storage-ee0e1ba4160428-staging",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
